name: Dispatch Cleanup Old Artifacts

on:
  repository_dispatch:
    types: [cleanup-old-artifacts]

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cleaning up artifacts for: ${{ github.event.client_payload.services }}"
          for SERVICE in $(echo '${{ github.event.client_payload.services }}' | jq -r '.[]'); do
            echo "Processing $SERVICE ..."
            gh api repos/${{ github.repository }}/actions/artifacts \
              --paginate --jq ".artifacts[] | select(.name==\"${SERVICE}-jar\") | .id + \"|\" + .created_at" > all_artifacts.txt

            COUNT=$(wc -l < all_artifacts.txt)
            if [ "$COUNT" -le 3 ]; then
              echo "Only $COUNT artifacts found for $SERVICE — nothing to clean."
              continue
            fi

            # Keep latest 3 (sort newest first)
            sort -r -t'|' -k2 all_artifacts.txt | tail -n +4 | cut -d'|' -f1 > old_ids.txt

            echo "Deleting old artifacts for $SERVICE..."
            while read -r ID; do
              gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$ID || true
            done < old_ids.txt
          done