name: Dispatch Cleanup Old Artifacts

on:
  repository_dispatch:
    types: [cleanup-old-artifacts]

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Convert the services payload into JSON array for jq
          SERVICES_JSON="${{ toJson(github.event.client_payload.services) }}"
          echo "Cleaning up artifacts for services: $SERVICES_JSON"

          # Iterate over each service
          for SERVICE in $(echo "$SERVICES_JSON" | jq -r '.[]'); do
            echo "Processing $SERVICE ..."

            # Get all artifacts for this service
            ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts \
              --paginate --jq ".artifacts[] | select(.name==\"${SERVICE}-jar\") | [.id, .created_at] | @tsv")

            COUNT=$(echo "$ARTIFACTS" | wc -l)
            if [ "$COUNT" -le 3 ]; then
              echo "Only $COUNT artifacts found for $SERVICE — nothing to clean."
              continue
            fi

            # Keep latest 3, delete older
            echo "$ARTIFACTS" | sort -k2 -r | tail -n +4 | cut -f1 | while read -r ID; do
              echo "Deleting artifact $ID for $SERVICE ..."
              gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$ID || true
            done
          done
