name: Deploy Calowin Services to Hugging Face

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed services
        id: set-matrix
        run: |
          services=("CalowinAccount" "CalowinFriends" "CalowinNotification" "CalowinSpringNode" "CalowinTrip" "CalowinWellnessZone")
          changed_services=()

          for s in "${services[@]}"; do
            changed_src=true
            changed_other=true

            if [ "$changed_src" = true ] || [ "$changed_other" = true ]; then
              changed_services+=("{\"service\":\"$s\",\"changed_src\":$changed_src,\"changed_other\":$changed_other}")
            fi
          done

          if [ ${#changed_services[@]} -eq 0 ]; then
            echo 'matrix={"include":[]}' >> $GITHUB_OUTPUT
            echo "No services changed"
          else
            matrix_json="{\"include\":[$(IFS=, ; echo "${changed_services[*]}")]}"
            echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
            echo "Changed services: $matrix_json"
          fi

  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up JDK
        if: ${{ matrix.changed_src }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        if: ${{ matrix.changed_src }}
        run: |
          cd ${{ matrix.service }}
          mvn clean package -DskipTests
          echo "Contents of target folder:"
          ls -lh target/
          cd ..

      - name: Prepare upload folder
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/${{ matrix.service }} hf_upload/${{ matrix.service }}

          cd hf_upload/${{ matrix.service }}
          git checkout main || git checkout -b main
          cd ../..

          cp ${{ matrix.service }}/target/*-SNAPSHOT.jar hf_upload/${{ matrix.service }}/
          cp ${{ matrix.service }}/Dockerfile hf_upload/${{ matrix.service }}/ || true
          cp ${{ matrix.service }}/README.md hf_upload/${{ matrix.service }}/ || true
#          cp ../../${{ matrix.service }}/target/*-SNAPSHOT.jar .
#          cp ../../${{ matrix.service }}/Dockerfile . || true
#          cp ../../${{ matrix.service }}/README.md . || true

      - name: Push to Hugging Face
        run: |
          cd hf_upload/${{ matrix.service }}
          git config user.name "CI Bot"
          git config user.email "ci-bot@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Deploy ${{ matrix.service }} build"
            git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/${{ matrix.service }} main
          else
            echo "No changes to commit for ${{ matrix.service }}"
          fi
